name: Release Branch Activity

on:
  push:
    branches:
      - 'release/**'
  pull_request:
    branches:
      - 'release/**'

jobs:
  hello-world:
    runs-on: ubuntu-latest
    #if: github.event.commits[0].message != 'Initial commit' && github.event.head_commit.message != 'Initial commit'
    steps:
      - name: Say Hello
        run: echo "Hello World"
